### ISSUE TITLE
Clean UP & Dockerization eos9c7k

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos9c7k#1]

**Comment by pittmanriley** [comment]
Hi @GemmaTuron, I'm finished refactoring this model, but I noticed something odd when I was testing to make sure it works. When I tested this model both before refactoring and after, it would produce normal outputs for most smiles inputs, but sometimes produces a null. For example: 


```
ersilia run -i "COc1cc(NC(=O)c2ccc(-c3ccc(Cl)cc3)o2)cc(OC)c1"
{
    "input": {
        "key": "VHKBTPQDHDSBSP-UHFFFAOYSA-N",
        "input": "COc1cc(NC(=O)c2ccc(-c3ccc(Cl)cc3)o2)cc(OC)c1",
        "text": "COc1cc(NC(=O)c2ccc(-c3ccc(Cl)cc3)o2)cc(OC)c1"
    },
    "output": {
        "products": [
            "['COc1ccc(NC(=O)c2ccc(Br)o2)cc1', 'Cc1cc(on1)C(=O)Nc1ccc(Cl)cc1', 'COc1ccc(Cl)cc1-c1ccc(o1)C([O-])=O', 'Clc1cc(Cl)cc(NC(=O)c2ccno2)c1', 'COc1ccc(NC(=O)c2ccco2)cc1', 'COc1ccc(NC(=O)c2cc(C)no2)cc1', 'CC(=O)Nc1cc(n[nH]1)-c1ccc(Cl)cc1', 'COc1cc(NC(=O)C(C)C)cc(OC)c1', 'Clc1ccc(NC(=O)c2ccco2)cc1', 'COc1cc(NC(=O)C(F)(F)F)cc(OC)c1', 'COc1ccc(cc1)-n1cc(nn1)C([O-])=O', 'Cc1ocnc1C(=O)Nc1ccc(Cl)cc1', 'Clc1ccc(NC(=O)c2ccc(Br)o2)c(Cl)c1', 'COc1cccc(NC(=O)C2=COCCO2)c1', 'CC(=O)Nc1c(oc2ccc(Cl)cc12)C([O-])=O', 'Cc1cc(NC(=O)c2cc(Cl)ccc2Cl)no1', 'Clc1ccc(Cl)c(c1)C(=O)Nc1cccnc1', 'COc1ccc(OC(C)CNC(C)=O)cc1', 'COc1cccc(NC(=O)c2cccnc2)c1', 'COc1ccc(NC(=O)c2cc(C)on2)cc1', 'Clc1ccc(Cl)c(c1)C(=O)Nc1ccncc1', 'COc1ccc(cc1)-n1cc(Cl)ccc1=O', 'Cc1cc(on1)C(=O)Nc1ccc(F)c(Cl)c1', 'COc1ccc(cc1)C(=O)Nc1cc(C)on1', 'Cc1c(oc2ccc(Cl)cc12)C([O-])=O', 'COc1ccc(cc1)-n1cc(Cl)nc(Cl)c1=O', 'COc1ccc(Cl)cc1C(=O)NCC(C)C', 'COc1ccc(Cl)cc1C(=O)Nc1nccs1', 'COc1ccc(NC(=O)c2cccnc2)cc1', 'Oc1ccc(Cl)cc1NC(=O)c1ccco1', 'COc1ccc(cc1)C(=O)Nc1cccnc1', 'Clc1ccc(NC(=O)c2ccno2)cc1Cl', 'COc1nc(Cl)cn(-c2ccc(Cl)cc2)c1=O', 'Cc1nnsc1C(=O)Nc1cc(Cl)ccc1Cl', 'COc1ccc(cc1)-c1cc(no1)C([O-])=O', 'Clc1ccc(Cl)c(NC(=O)c2cn[nH]n2)c1', 'Clc1ccc(NC(=O)c2ccsn2)cc1', 'Cc1cc(NC(=O)c2ccc(Cl)cc2Cl)no1', 'COc1ccc(cc1)-c1cc([nH]n1)C(=O)NN', 'NNC(=O)c1cc(on1)-c1ccc(Cl)cc1', 'COc1cccc(NC(=O)c2ccccc2)c1', 'COc1cccc(NC(=O)c2ccncc2)c1', '[O-]c1ccc(Cl)cc1C(=O)Nc1cccnc1', 'COc1ccc(NC(=O)c2nc[nH]n2)cc1', 'Cc1c(nnn1-c1ccc(Cl)cc1)C([O-])=O', 'Cn1nccc1C(=O)Nc1cc(Cl)ccc1Cl', 'COc1ccc(NC(=O)c2c[nH]cn2)cc1', 'COC(=O)c1cc(on1)-c1ccc(OC)cc1', 'COc1ccc(NC(=O)c2ccccc2)cc1', 'COc1cccc(c1)C(=O)Nc1cc(C)on1', 'COc1ccc(Cl)cc1NC(=O)CC(C)=O', 'COc1ccc(NC=CC(=O)C(F)(F)F)cc1', 'Clc1ccc(C(=O)Nc2ccncc2)c(Cl)c1', 'Cc1nnsc1C(=O)Nc1ccc(Cl)cc1', 'COC(=O)c1noc(n1)-c1ccc(OC)cc1', 'COc1cccc(NC(=O)CCP(O)([O-])=O)c1', 'COc1ccc(Cl)cc1C(=O)NCC[NH+](C)C', 'COc1cccc(NC(=O)c2cccnn2)c1', 'COc1ccc(cc1)S(=O)(=O)NC(C)C([O-])=O', 'COC(=O)c1c(C)noc1-c1ccc(Cl)cc1', 'CC(=O)c1c(C)onc1-c1ccc(Cl)cc1Cl', 'CC(C)(Oc1ccc(Cl)cc1)C(=O)NC1CC1', 'COc1ccc(NC(=O)C(Cl)Cl)cc1', 'COc1ccc(Cl)cc1C(=O)NC(C)C', 'COc1cccc(c1)C(=O)Nc1cccnc1', 'COc1ccc(cc1)C(=O)Nc1ccccc1', 'COc1ccc2CC(CNC(C)=O)c2c1', 'COc1ccc(cc1)S(=O)(=O)NC(C)C([O-])=O', 'CNC(=O)c1oc(nc1C)-c1ccc(Cl)cc1', 'Cc1c(oc2cc(Cl)ccc12)C([O-])=O', 'COc1ccc(Cl)cc1C(=O)NCC#N', 'Cc1noc(C(=O)Nc2ccc(Cl)cc2)c1Cl', 'COc1cccc(c1)C(=O)Nc1ccncc1', 'CNC(=O)c1csc(n1)-c1ccc(Cl)cc1', 'Cc1nnsc1C(=O)Nc1ccc(Cl)cc1Cl', 'COc1ccc(OC)c(c1)C(C)NC(C)=O', 'COc1ccc(cc1)N1CC[NH2+]C(C1)C(N)=O', 'COc1ccc(NC(=O)c2ccccn2)cc1', 'COC(=O)c1cc([nH]n1)-c1ccc(OC)cc1', 'COc1ccc(cc1)C(=O)NN', 'CCOCCC(=O)Nc1cc(Cl)ccc1OC', 'COc1ccc(cc1)-c1cnc(NC(C)=O)[nH]1', 'COc1ccc2nc(Cl)cc(Cl)c2c1', 'CNC(=O)c1ccc(s1)-c1ccc(OC)cc1', 'CC(=O)Nc1c(oc2ccc(Cl)cc12)C(N)=O', 'Cc1cc(no1)C(=O)Nc1cc(Cl)ccc1O', 'Clc1ccc(NC(=O)c2cn[nH]n2)c(Cl)c1', 'ClC(Cl)C(=O)Nc1cc(Cl)ccc1Cl', 'COc1ccc(NC(=O)c2cccnn2)cc1', 'NC(=O)NOCc1ccc(Cl)cc1Cl', 'COc1ccccc1C(=O)Nc1ccccc1', 'COc1ccc(C=CNC(C)=O)cc1', 'COc1ccc(NC(=O)C(C)C)cc1', 'COc1ccc(OCCNC(C)=O)cc1', 'COc1cc(C)c(NC(=O)C(C)[NH3+])c(C)c1', 'COc1ccc(cc1)C(=O)NC(C)C([O-])=O', 'CC(C)OC(=O)NNc1cc(Cl)ccc1Cl', 'COc1ccc(NC(=O)c2coc(C)c2)cc1', 'COc1ccc(NC(=O)CC(C)=O)cc1', 'COc1ccc(NC(=O)C([O-])=O)cc1']",
            "['0.51', '0.51', '0.53', '0.54', '0.54', '0.54', '0.55', '0.56', '0.56', '0.57', '0.57', '0.57', '0.58', '0.59', '0.59', '0.59', '0.6', '0.6', '0.6', '0.6', '0.6', '0.6', '0.6', '0.6', '0.6', '0.6', '0.61', '0.61', '0.61', '0.61', '0.61', '0.61', '0.61', '0.62', '0.62', '0.62', '0.62', '0.62', '0.62', '0.62', '0.62', '0.62', '0.62', '0.62', '0.62', '0.62', '0.62', '0.63', '0.63', '0.63', '0.63', '0.63', '0.63', '0.63', '0.63', '0.63', '0.63', '0.63', '0.63', '0.63', '0.63', '0.63', '0.63', '0.63', '0.63', '0.63', '0.63', '0.63', '0.63', '0.63', '0.63', '0.63', '0.64', '0.64', '0.64', '0.64', '0.64', '0.64', '0.64', '0.64', '0.64', '0.64', '0.64', '0.64', '0.64', '0.64', '0.64', '0.64', '0.64', '0.65', '0.65', '0.65', '0.65', '0.65', '0.65', '0.65', '0.65', '0.65', '0.65', '0.65']"
        ]
    }
}
```


However, the following input produces a null: 

```
ersilia run -i "C[C@@H]1CCCN1CCc1cc2cc(-c3ccc(C#N)cc3)ccc2o1"
{
    "input": {
        "key": "KFHYZKCRXNRKRC-MRXNPFEDSA-N",
        "input": "C[C@@H]1CCCN1CCc1cc2cc(-c3ccc(C#N)cc3)ccc2o1",
        "text": "C[C@@H]1CCCN1CCc1cc2cc(-c3ccc(C#N)cc3)ccc2o1"
    },
    "output": {
        "products": [
            null,
            null
        ]
    }
}
```

I tested this on the first 138 lines of the eml_canonical file and there doesn't seem to be a pattern of when it produces null. Here is the output in case you'd like to see: 
[eos9c7k_output.csv](https://github.com/ersilia-os/eos9c7k/files/12176630/eos9c7k_output.csv)

**Comment by GemmaTuron** [comment]
Hi @pittmanriley 

One question, is this the output produced by the Ersilia CLI? because the format is very difficult to read, and we should be getting something like what @ZakiaYahya is shwoing for model eos4q1a
About some molecules failing, it is possible, what is the proportion?

Thanks

**Comment by pittmanriley** [comment]
@GemmaTuron Yes I created it with Ersilia CLI. I will try this out with Docker and Colab to make sure this is consistent. And out of the 138 molecules that I tested out in the partial eml_canonical file, 20 of them came out as null.

**Comment by GemmaTuron** [comment]
Ok, I would not worry about the null values at this point, but we do need to work on how the output is processed, because we should be getting something like the attached file. Can you compare with the eos4q1a where the example comes from and see why we do not have the typical Ersilia output with the key and smiles as first columns?

[output_repo_path.csv](https://github.com/ersilia-os/eos9c7k/files/12179956/output_repo_path.csv)

**Comment by pittmanriley** [comment]
Hi @GemmaTuron, I realized that the output for this model is working correctly, I just accidentally sent you the output from the terminal. After running it again and specifying an output file, it behaves as expected: 
[eos9c7k.csv](https://github.com/ersilia-os/eos9c7k/files/12186854/eos9c7k.csv)

I will go ahead and submit the PR.

**Comment by pittmanriley** [comment]
I forgot about the current GitHub issues, so the PR failed. It should be ready to go whenever that issue is resolved.

**Comment by pittmanriley** [comment]
Hi @GemmaTuron, I submitted the PR and all the actions passed. We should be good to go with this model.

**Comment by GemmaTuron** [comment]
Perfect thanks @pittmanriley 

I think you missed it in the Slack channel, we have found that some SMILES strings break the URL, hence causing the calculations to fail. You can see the discussion in this model from Febie's model [eos4b8j](https://github.com/ersilia-os/eos4b8j/issues/1).
We need to change the smiles to a url compatible format, with urllib
This would be an example code snippet:
```
Lines = [
    "[Ca++].NC1=NC(=O)C2=C(NCC(CNc3ccc(cc3)C(=O)N[C@@H](CCC([O-])=O)C([O-])=O)N2C=O)N1"
]

fp     = 'ECfp4'
db     = 'GDBChEMBL'
nnc    = '100'

data = []
for input_smiles in Lines:
    input_smiles = input_smiles.strip() 
    url_encoded_smiles = urllib.parse.quote(input_smiles)

    url = 'https://gdb-chembl-simsearch.gdb.tools/search?smi=' + url_encoded_smiles +  '&fp=' + fp + '&db=' + db + '&nnc=' + nnc
    print(url)
    #r = requests.get(url)
```

if you just run this and print the input smiles and the encoded smiles you will see the difference!

**Comment by pittmanriley** [comment]
Thank you @GemmaTuron! These changes are reflected in the PR.

**Comment by pittmanriley** [comment]
Hi @GemmaTuron, I wanted to ask a quick question about the output of this model now compared to what it looked like a few days ago before I made the changes. Before, it outputted a list of similar molecules and also showed a list of floats. This is the old output here: 
[old_output.csv](https://github.com/ersilia-os/eos9c7k/files/12257160/old_output.csv)

However, now that I made the changes, those floats are no longer there. Is this okay? Why were those floats there originally? Here is the new, updated output: 
[eos9c7k_cli.csv](https://github.com/ersilia-os/eos9c7k/files/12257178/eos9c7k_cli.csv)

I made these changes based on eos7jlv, which the output also doesn't have floats. I think the update is correct, but I wanted to make sure I understood why this happened.

**Comment by GemmaTuron** [comment]
Hi @pittmanriley 
In the original code, this is how we got the output:
```
data+= [[smiles_list, similarity_indices]]
with open(sys.argv[2], 'w') as f:
    json.dump(data, f)
```
As it indicates, you get the smiles and a measure of similarity of the new molecule with the input molecule. In the refactored code, you are passing only d[0], so, the smiles, and d[1] is not saved - this is just to simplify the output. If similarity wants to be captured, it can be measured with other tools
```
data+= [[smiles_list, similarity_indices]]
header = ["sim-{0}".format(i+1) for i in range(len(smiles_list))]
with open(sys.argv[2], "w") as f:
with open(sys.argv[2], 'w') as f:
    writer = csv.writer(f)
    writer.writerow(header)
    for d in data:
        writer.writerow(d[0])
```

**Comment by GemmaTuron** [comment]
Before merging the PR, could you please rename the file to main.py?

**Comment by pittmanriley** [comment]
@GemmaTuron this makes sense, thank you!
